import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })
import Header from '../../components/Header';
import Banner from '../../components/Banner';
import { client } from '../../sanity.config';

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    title,
    description,
    slug,
    mainImage,
    author -> {
      name,
      image
    }
  }`;

  const posts = await client.fetch(query);

  return {
    props: {
      posts
    }
  }
}

import { Post } from '../../typings';
import Posts from '../../components/Posts';

interface Props {
  posts: Post[];
}


export default function Home({ posts }: Props) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>This is Blog Application</h1> */}
      <Header />
      <Banner />
      <Posts posts={posts} />
    </>
  )
}
